import { DetailedClient } from "./types";

export const ALL_CLIENTS: DetailedClient[] = [
  {
    id: "1",
    clientId: "#BD13343",
    name: "Jane Doe",
    caseType: "Employment Dispute",
    email: "jane.doe@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "March 10, 2025",
    conflictStatus: "Active",
    address: "123 Victoria Island, Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Tech Solutions Ltd",
    preferredContact: "Email",
    linkedCases: [
      {
        id: "c1",
        title: "Wrongful Termination Claim",
        caseNumber: "LD/142/2025",
        status: "Active",
        caseType: "Employment Dispute",
        filingDate: "March 12, 2025",
        jurisdiction: "Lagos State High Court",
      }
    ],
    documents: [
      {
        id: "d1",
        name: "Employment Contract.pdf",
        type: "Contract",
        dateUploaded: "Mar 15, 2025",
        size: "2.4 MB",
      },
      {
        id: "d2",
        name: "ID Card - National ID.pdf",
        type: "Identification",
        dateUploaded: "Mar 14, 2025",
        size: "1.2 MB",
      },
      {
        id: "d3",
        name: "Termination Letter.pdf",
        type: "Legal Document",
        dateUploaded: "Mar 10, 2025",
        size: "856 KB",
      },
      {
        id: "d4",
        name: "Witness Statement.pdf",
        type: "Evidence",
        dateUploaded: "Mar 8, 2025",
        size: "3.1 MB",
      }
    ]
  },
  {
    id: "2",
    clientId: "#BD13343",
    name: "Ibrahim Yusuf",
    caseType: "Land Dispute",
    email: "ibrahim.yusuf@firmmail.com",
    conflict: "Potential Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "March 08, 2025",
    conflictStatus: "Active",
    address: "Plot 15, Admiralty Way, Lekki",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Yusuf Properties",
    preferredContact: "Phone",
    linkedCases: [
      {
        id: "c2",
        title: "Lekki Land Title Dispute",
        caseNumber: "LD/285/2025",
        status: "Active",
        caseType: "Land Dispute",
        filingDate: "March 09, 2025",
        jurisdiction: "Lagos State High Court",
      }
    ],
    documents: [
      {
        id: "d5",
        name: "Land Survey Plan.pdf",
        type: "Survey",
        dateUploaded: "Mar 09, 2025",
        size: "4.8 MB",
      },
      {
        id: "d6",
        name: "Deed of Assignment.pdf",
        type: "Deed",
        dateUploaded: "Mar 08, 2025",
        size: "3.2 MB",
      }
    ]
  },
  {
    id: "3",
    clientId: "#BD13343",
    name: "Zainab Bello",
    caseType: "Contract Review",
    email: "z.bello@startuplaw.com",
    conflict: "Confirmed Conflict",
    phone: "+234 803 123 4567",
    clientType: "Corporate",
    dateRegistered: "March 05, 2025",
    conflictStatus: "Pending",
    address: "A01, Wuse II",
    state: "FCT",
    lga: "Abuja Municipal",
    nationality: "Nigerian",
    workplace: "Startup Law Corp",
    preferredContact: "Email",
    linkedCases: [
      {
        id: "c3",
        title: "SaaS Agreement Dispute",
        caseNumber: "FHC/ABJ/CS/55/25",
        status: "Pending Check",
        caseType: "Contract Review",
        filingDate: "March 06, 2025",
        jurisdiction: "Federal High Court, Abuja",
      }
    ],
    documents: [
      {
        id: "d7",
        name: "Draft SaaS Agreement.docx",
        type: "Agreement",
        dateUploaded: "Mar 05, 2025",
        size: "1.1 MB",
      }
    ]
  },
  {
    id: "4",
    clientId: "#BD13343",
    name: "Victor Ade",
    caseType: "Divorce & Custody",
    email: "vade@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 28, 2025",
    conflictStatus: "Active",
    address: "45 Allen Avenue, Ikeja",
    state: "Lagos",
    lga: "Ikeja",
    nationality: "Nigerian",
    workplace: "Independent Consultant",
    preferredContact: "Phone",
    linkedCases: [
      {
        id: "c4",
        title: "Dissolution of Marriage",
        caseNumber: "ID/983/HD/2025",
        status: "Active",
        caseType: "Divorce & Custody",
        filingDate: "March 02, 2025",
        jurisdiction: "Ikeja High Court",
      }
    ],
    documents: [
      {
        id: "d8",
        name: "Marriage Certificate.pdf",
        type: "Certificate",
        dateUploaded: "Mar 01, 2025",
        size: "950 KB",
      }
    ]
  },
  {
    id: "5",
    clientId: "#BD13343",
    name: "Minabo Opuogbo",
    caseType: "Accommodation",
    email: "Mina@gmail.com",
    conflict: "Potential Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 25, 2025",
    conflictStatus: "Active",
    address: "12 Marine Road, Apapa",
    state: "Lagos",
    lga: "Apapa",
    nationality: "Nigerian",
    workplace: "Apapa Port Authority",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "6",
    clientId: "#BD13343",
    name: "Amarachi Nwankwo",
    caseType: "Salary Disbursement",
    email: "AmaraNwa@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 20, 2025",
    conflictStatus: "Active",
    address: "9 Gbagada Expressway",
    state: "Lagos",
    lga: "Kosofe",
    nationality: "Nigerian",
    workplace: "Fintech Solutions",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "7",
    clientId: "#BD13343",
    name: "Simisola Ilesanmi",
    caseType: "Training Issue",
    email: "SSimi@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 15, 2025",
    conflictStatus: "Active",
    address: "24 Bode Thomas, Surulere",
    state: "Lagos",
    lga: "Surulere",
    nationality: "Nigerian",
    workplace: "Skillup Academy",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "8",
    clientId: "#BD13343",
    name: "Umar Jibrin",
    caseType: "Tax Payments non payment",
    email: "Umarj@gmail.com",
    conflict: "Confirmed Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 10, 2025",
    conflictStatus: "Inactive",
    address: "Plot 89, Gwarinpa Estate",
    state: "FCT",
    lga: "Abuja Municipal",
    nationality: "Nigerian",
    workplace: "Jibrin & Sons Ltd",
    preferredContact: "Phone",
    linkedCases: [],
    documents: []
  },
  {
    id: "9",
    clientId: "#BD13344",
    name: "Chidi Okonkwo",
    caseType: "Property Dispute",
    email: "chidi.okonkwo@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 05, 2025",
    conflictStatus: "Active",
    address: "18 Awolowo Road, Ikoyi",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Real Estate Partners",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "10",
    clientId: "#BD13345",
    name: "Funke Akindele",
    caseType: "Commercial Litigation",
    email: "funke.a@firmlaw.com",
    conflict: "Potential Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "February 01, 2025",
    conflictStatus: "Active",
    address: "6 Chevron Drive, Lekki",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "SceneOne Productions",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "11",
    clientId: "#BD13346",
    name: "Tunde Fashola",
    caseType: "Criminal Defense",
    email: "tunde.f@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "January 28, 2025",
    conflictStatus: "Active",
    address: "5 Bourdillon Rd, Ikoyi",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Self Employed",
    preferredContact: "Phone",
    linkedCases: [],
    documents: []
  },
  {
    id: "12",
    clientId: "#BD13347",
    name: "Ngozi Adeyemi",
    caseType: "Family Law",
    email: "ngozi.a@startuplaw.com",
    conflict: "Confirmed Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "January 25, 2025",
    conflictStatus: "Inactive",
    address: "24 Banana Island, Ikoyi",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Adeyemi Legal Partners",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "13",
    clientId: "#BD13348",
    name: "Emeka Eze",
    caseType: "Intellectual Property",
    email: "emeka.eze@gmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "January 22, 2025",
    conflictStatus: "Active",
    address: "14 Ogunlana Drive, Surulere",
    state: "Lagos",
    lga: "Surulere",
    nationality: "Nigerian",
    workplace: "Eze Creative Agency",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "14",
    clientId: "#BD13349",
    name: "Aisha Mohammed",
    caseType: "Immigration Law",
    email: "aisha.m@firmmail.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "January 18, 2025",
    conflictStatus: "Active",
    address: "8 Yusuf Lule Street, Victoria Island",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Multinational Oil & Gas",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "15",
    clientId: "#BD13350",
    name: "Babatunde Olatunji",
    caseType: "Banking & Finance",
    email: "baba.t@gmail.com",
    conflict: "Potential Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "January 15, 2025",
    conflictStatus: "Active",
    address: "17 Ademola Adetokunbo, Victoria Island",
    state: "Lagos",
    lga: "Eti-Osa",
    nationality: "Nigerian",
    workplace: "Zenith Bank PLC",
    preferredContact: "Email",
    linkedCases: [],
    documents: []
  },
  {
    id: "16",
    clientId: "#BD13351",
    name: "Chioma Obi",
    caseType: "Maritime Law",
    email: "chioma.obi@firmlaw.com",
    conflict: "No Conflict",
    phone: "+234 803 123 4567",
    clientType: "Individual",
    dateRegistered: "January 10, 2025",
    conflictStatus: "Active",
    address: "32 Creek Road, Apapa",
    state: "Lagos",
    lga: "Apapa",
    nationality: "Nigerian",
    workplace: "Obi Shipping Services",
    preferredContact: "Phone",
    linkedCases: [],
    documents: []
  }
];
